package main

import (
	"html/template" // We can use html/template to keep the HTML in a separate file,
	"log"           // allowing us to change the layout of our edit page without modifying the underlying Go code.
	"net/http"      // The html/template package helps guarantee that only safe and correct-looking HTML is generated by template actions.
	"os"
	"regexp"
)

func main() {
	http.HandleFunc("/view/", makeHandler(viewHandler)) // http.HandleFunc. It takes an http.ResponseWriter and an http.Request as its arguments.
	http.HandleFunc("/edit/", makeHandler(editHandler)) // An http.ResponseWriter value assembles the HTTP server's response;
	http.HandleFunc("/save/", makeHandler(saveHandler)) // by writing to it, we send data to the HTTP client.
	// An http.Request is a data structure that represents the client HTTP request. r.URL.Path is the path component of the request URL.

	log.Fatal(http.ListenAndServe(":8080", nil)) // ListenAndServe always returns an error, since it only returns when an unexpected error occurs.
	// In order to log that error we wrap the function call with log.Fatal.
}

type Page struct { // The Page struct describes how page data will be stored in memory.
	Title string
	Body  []byte
}

func (p *Page) save() error { // But what about persistent storage? We can address that by creating a save method on Page;
	// This method's signature reads: "This is a method named save that takes as its receiver p, a pointer to Page.
	// It takes no parameters, and returns a value of type error."
	filename := p.Title + ".txt"
	return os.WriteFile(filename, p.Body, 0600) //  If all goes well, Page.save() will return nil (the zero-value for pointers, interfaces, and some other types).
}

// The octal integer literal 0600, passed as the third parameter to WriteFile,
// indicates that the file should be created with read-write permissions for the current user only.

// In addition to saving pages, we will want to load pages, too:
func loadPage(title string) (*Page, error) {
	filename := title + ".txt"
	body, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}
	return &Page{Title: title, Body: body}, nil
}

func viewHandler(w http.ResponseWriter, r *http.Request, title string) {
	p, err := loadPage(title)
	if err != nil {
		http.Redirect(w, r, "/edit/"+title, http.StatusFound)
		return
	}
	renderTemplate(w, "view", p)
}

func editHandler(w http.ResponseWriter, r *http.Request, title string) {
	p, err := loadPage(title)
	if err != nil {
		p = &Page{Title: title}
	}
	renderTemplate(w, "edit", p)
}

func saveHandler(w http.ResponseWriter, r *http.Request, title string) {
	body := r.FormValue("body")
	p := &Page{Title: title, Body: []byte(body)}
	err := p.save() // If all goes well, Page.save() will return nil (the zero-value for pointers, interfaces, and some other types).
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	http.Redirect(w, r, "/view/"+title, http.StatusFound)
}

var templates = template.Must(template.ParseFiles("edit.html", "view.html")) // template.ParseFiles will read the contents of edit.html and view.html and
// return a *template.Template.

func renderTemplate(w http.ResponseWriter, tmpl string, p *Page) { // A function to remove duplication of code from viewHandler and editHandler

	// Notice that we've used almost exactly the same templating code in both handlers. Let's remove this duplication by moving the templating code to its own function:

	err := templates.ExecuteTemplate(w, tmpl+".html", p) // The method t.Execute executes the template, writing the generated HTML to the http.ResponseWriter.
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

var validPath = regexp.MustCompile("^/(edit|save|view)/([a-zA-Z0-9]+)$")

func makeHandler(fn func(http.ResponseWriter, *http.Request, string)) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		m := validPath.FindStringSubmatch(r.URL.Path) // r.URL.Path is the path component of the request URL.
		if m == nil {
			http.NotFound(w, r)
			return
		}
		fn(w, r, m[2])
	}
}

/*ascii-art-web-application*/
